---
fixtures:
  repositories:
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yum: https://github.com/voxpupuli/puppet-yum.git
